name: C Program Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make

    - name: Compile program
      run: make
    
    - name: Check if compilation succeeded
      run: |
        if [ -f ./program ]; then
          echo "Compilation successful!"
        else
          echo "Compilation failed!"
          exit 1
        fi
    
    - name: Upload compiled binary
      uses: actions/upload-artifact@v3
      with:
        name: c-program-binary
        path: ./program
        retention-days: 7